---
version: "3"
services:
 devopsdb:
   image: pranay419/mynewapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: pranay419/mynewapp:appimage
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
